# Generated by Django 2.1.7 on 2019-06-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_notes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='image',
            new_name='images',
        ),
    ]
