# Generated by Django 2.1.7 on 2019-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190617_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], default='Green', max_length=50, null=True),
        ),
    ]
