# Generated by Django 2.1.7 on 2019-06-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190611_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
