# Generated by Django 2.1.7 on 2019-06-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190611_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='images',
        ),
        migrations.AddField(
            model_name='labels',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
