# Generated by Django 2.1.7 on 2019-06-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_notes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
    ]
