# Generated by Django 2.1.7 on 2019-05-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_userprofileinfo_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
