# Generated by Django 2.1.7 on 2019-06-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
