# Generated by Django 2.1.7 on 2019-05-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20190525_0457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
