# Generated by Django 2.1.7 on 2019-05-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
