# Generated by Django 2.1.7 on 2019-07-11 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]', 'Only Alphabetical Characters are allowed.')])),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Title')),
                ('description', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]', 'Only Alphabetical Characters are allowed.')], verbose_name='Description')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('remainder', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, choices=[('Red', 'Red'), ('Ged', 'Green'), ('Blue', 'Blue')], default='Green', max_length=50, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('trash', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fundooapp.Notes'),
        ),
    ]
