# Generated by Django 2.1.7 on 2019-07-11 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundooapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='created_by',
        ),
        migrations.AddField(
            model_name='notes',
            name='created_by',
            field=models.ManyToManyField(related_name='notes_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
