# Generated by Django 2.1.7 on 2019-07-17 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsmodel',
            name='region',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^ap-[a-z]*-[1]{1}$', 'Please follow the region format.')]),
        ),
    ]
