# Generated by Django 2.1.7 on 2019-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsmodel',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
