# Generated by Django 2.1.7 on 2019-07-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0002_auto_20190711_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='created_by',
            new_name='collaborator',
        ),
    ]
