# Generated by Django 2.1.7 on 2019-06-17 10:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0002_auto_20190617_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=400, validators=[django.core.validators.RegexValidator(code='invalid Title', message='Title must be Alphanumeric', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
