# Generated by Django 2.1.7 on 2019-07-11 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0003_auto_20190711_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='collaborator',
            field=models.ManyToManyField(related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
