# Generated by Django 2.1.7 on 2019-07-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0004_contentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmodel',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='contentmodel',
            old_name='created',
            new_name='pub_date',
        ),
    ]
