# Generated by Django 2.1.7 on 2019-06-18 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0005_auto_20190618_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='text',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]', 'Only Alphabetical Characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]', 'Only Alphabetical Characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='notes',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=400, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
