# Generated by Django 2.1.7 on 2019-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0006_auto_20190618_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=True),
        ),
    ]
