# Generated by Django 2.1.7 on 2019-06-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0012_auto_20190624_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
