# Generated by Django 2.1.7 on 2019-06-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0013_auto_20190625_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
