# Generated by Django 2.1.7 on 2019-06-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0014_notes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='slug',
        ),
    ]
