# Generated by Django 2.1.7 on 2019-06-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0015_remove_notes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
