# Generated by Django 2.1.7 on 2019-07-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0016_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
