# Generated by Django 2.1.7 on 2019-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0017_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
