# Generated by Django 2.1.7 on 2019-07-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0019_remove_notes_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
