# Generated by Django 2.1.7 on 2019-07-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0020_awsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Ged', 'Green'), ('Blue', 'Blue')], default='Green', max_length=50, null=True),
        ),
    ]
